name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.SAKURA_HOST }}"
          username: sazumyy
          password: 9+AG.d9C2PH2
          #TODO: このコマンドだと延々とキーがファイルに書き込まれてしまう上に、想定通り動作しないので修正したい
          script: |
            cd /home/sazumyy/www/kotori_bunko
            git pull origin main
            echo '<script async="" src="https://maps.googleapis.com/maps/api/js?key=${{ secrets.GOOGLE_MAP_API_KEY }}&callback=console.debug&amp&libraries=maps,marker&amp&v=beta"></script>' >> index.html
            echo 'const token = "${{ secrets.INSTAGRAM_ACCESS_TOKEN_20240131 }}"; showIgMedia(token);' >> js/modules.js
